### ISSUE TITLE
Failure to load model

### ISSUE THREAD

**Issue by hukuda222** [r-three/RAD#1]
Thanks for sharing the code!
I tried to run your model `gpt2_sentiment/pytorch_model.bin`,  but got the following error.

```
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for GPT2RewardModel:
        Unexpected key(s) in state_dict: "model.transformer.h.0.attn.bias", "model.transformer.h.0.attn.masked_bias", "model.transformer.h.1.attn.bias", "model.transformer.h.1.attn.masked_bias", "model.transformer.h.2.attn.bias", "model.transformer.h.2.attn.masked_bias", "model.transformer.h.3.attn.bias", "model.transformer.h.3.attn.masked_bias", "model.transformer.h.4.attn.bias", "model.transformer.h.4.attn.masked_bias", "model.transformer.h.5.attn.bias", "model.transformer.h.5.attn.masked_bias", "model.transformer.h.6.attn.bias", "model.transformer.h.6.attn.masked_bias", "model.transformer.h.7.attn.bias", "model.transformer.h.7.attn.masked_bias", "model.transformer.h.8.attn.bias", "model.transformer.h.8.attn.masked_bias", "model.transformer.h.9.attn.bias", "model.transformer.h.9.attn.masked_bias", "model.transformer.h.10.attn.bias", "model.transformer.h.10.attn.masked_bias", "model.transformer.h.11.attn.bias", "model.transformer.h.11.attn.masked_bias".
``` 
If I set `rm.load_state_dict(state_dict)` to `rm.load_state_dict(state_dict,strict=False)` I could run it, but the quality of the output was not good.

**Comment by haikangdeng** [comment]
Hi there, have you installed the correct version of transformers and pytorch specified in the environment.yml file? It could be that newer versions of transformers changed the key names of model layers. I've followed the instructions to set up the project and didn't encounter the same problem. 

Note that calling `load_state_dict` with `strict=False` skips the unmatching layers, which means you won't be loading the correct bias weights, and the model would not work I assume. Please also check if you accidentally set the reward model bias to false, as all those unexpected keys are biases.
