### ISSUE TITLE
ModuleNotFoundError: No module named 'reward_model'

### ISSUE THREAD

**Issue by RadiantCrystal** [r-three/RAD#2]
Hi Authors, 

Thnaks for sharing the code of this interesting paper.

I have one doubt while running the code for sentiment analysis.
`DATASET=positive
BATCH_SIZE=4
LANGUAGE_MODEL=gpt2-large
TOPK=20
BETA=50
INVERSE=True

python eval_sentiment.py \
    --dataset $DATASET
    --batch_size $BATCH_SIZE \
    --lm $LANGUAGE_MODEL \
    --topk $TOPK \
    --beta $BETA \
    --inverse $INVERSE
`

But, I am getting issue `Traceback (most recent call last):
  File "/home/rima/RAD/eval_sentiment.py", line 11, in <module>
    from utils.utils import prepare_lm, get_rm_tokenizer
  File "/home/rima/RAD/utils/utils.py", line 21, in <module>
    from reward_model import GPT2RewardModel
ModuleNotFoundError: No module named 'reward_model'`

I have tried relative path but it is still not working. Could you please look into the issue? 
Note: I have installed the repo and downloaded the model as instructed.

**Comment by haikangdeng** [comment]
Hi, I believe you need to build the project before running those scripts. To build, run the command `pip install -e .` at the project level.

**Comment by RadiantCrystal** [comment]
> Hi, I believe you need to build the project before running those scripts. To build, run the command `pip install -e .` at the project level.

Hey, It did not work in this way! I have already tried. Also, I am facing several issues while training the reward model. Could you please help me with that? I have preference data i.e. chosen and rejected response. I want to train the model with that.
